name: integration tests
on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello testing"
