name: integration tests
on:
  push:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: dschep/install-pipenv-action@v1
      - run: |
          pipenv install
          pipenv run pytest
